import {
  LayoutDashboard, MapPinned, HandCoins, GraduationCap, HeartPulse,
  Truck, Trees, MessageSquareWarning, ShieldCheck, FileText,
} from 'lucide-react';

// Single source of truth for routes + sidebar + page metadata.
export const NAV = [
  {
    path: '/',
    key: 'overview',
    label: 'Executive Command',
    short: 'Command',
    icon: LayoutDashboard,
    audience: 'CM Office · Chief Secretary',
    desc: 'State-wide tribal welfare assurance & vulnerability intelligence.',
  },
  {
    path: '/district',
    key: 'district',
    label: 'District Intelligence',
    short: 'District',
    icon: MapPinned,
    audience: 'District Collector',
    desc: 'Block & village vulnerability drill-down and intervention priorities.',
  },
  {
    path: '/welfare',
    key: 'welfare',
    label: 'Welfare Assurance',
    short: 'Welfare',
    icon: HandCoins,
    audience: 'Tribal Development Dept.',
    desc: 'MahaDBT linkage, benefit funnel & delivery bottlenecks.',
  },
  {
    path: '/education',
    key: 'education',
    label: 'Education & Hostels',
    short: 'Education',
    icon: GraduationCap,
    audience: 'Tribal Dev. · School Education',
    desc: 'Scholarships, hostel utilization, dropout risk & skill readiness.',
  },
  {
    path: '/health',
    key: 'health',
    label: 'Nutrition & Health',
    short: 'Health',
    icon: HeartPulse,
    audience: 'Public Health · W&CD',
    desc: 'Malnutrition, maternal-child risk & health access intelligence.',
  },
  {
    path: '/migration',
    key: 'migration',
    label: 'Migration & Livelihood',
    short: 'Migration',
    icon: Truck,
    audience: 'Rural Dev. · Skill Dev.',
    desc: 'Seasonal migration corridors, MGNREGA, SHG & livelihood stress.',
  },
  {
    path: '/fra',
    key: 'fra',
    label: 'Land & Forest Rights',
    short: 'FRA',
    icon: Trees,
    audience: 'Forest · Tribal Dev.',
    desc: 'FRA claim pipeline, backlog & geo-tagged title status.',
  },
  {
    path: '/grievances',
    key: 'grievances',
    label: 'Grievance & Trust',
    short: 'Grievance',
    icon: MessageSquareWarning,
    audience: 'All Departments',
    desc: 'Citizen grievances, sentiment & resolution performance.',
  },
  {
    path: '/compliance',
    key: 'compliance',
    label: 'Responsible AI',
    short: 'Compliance',
    icon: ShieldCheck,
    audience: 'MahaIT · Audit',
    desc: 'Human-in-the-loop, DPDP, bias monitoring & cyber health.',
  },
  {
    path: '/reports',
    key: 'reports',
    label: 'Reports & Briefs',
    short: 'Reports',
    icon: FileText,
    audience: 'CM Office · Secretaries',
    desc: 'Auto-generated decision briefs, exports & escalation matrix.',
  },
];

export const navByPath = (path) => NAV.find((n) => n.path === path) || NAV[0];
